url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Dreaming in Data" # the name of your site, e.g. ACME Corp.

source: source

collections:
  pages:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
